[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install --prefix packages/admin']

[phases.build]
cmds = ['npm run build --prefix packages/admin']

[start]
cmd = 'npm start --prefix packages/admin'
